language: node_js
node_js:
  - 11.1.0
cache:
  directories:
    - "$HOME/.npm"
install:
  - npm ci
jobs:
  include:
    - stage: Build and test
      script:
        - npm run test
        - npm pack
    - stage: npm release
      script: npm build
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_AUTH_TOKEN'
        skip_cleanup: true
        on:
          tags: true
branches:
  only:
    - master
    - /^v[0-9]+.*$/
